image: continuumio/miniconda3:latest

tests:
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda env create -f segnet_env.yml
    - source activate segnet
    - pytest